name: gilbertorey
favicon: null
layout_spectrum: 0.49464
typography_spectrum: 0.3948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ce2602'
    - '#df8a15'
    - '#4a5046'
    - '#181111'
  brandStrength: 0.875
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
