name: gilberto rey
favicon: null
layout_spectrum: 0.74663
typography_spectrum: 0.3903879
title: news / insights
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#280000'
    - '#191919'
    - '#e9e9e9'
    - '#ff4040'
    - '#5d1010'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0
purpose: []
